import type { ReactNode } from "react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: ReactNode
}) {
  return <>{children}</>
}
